transfer_data:
  transfer_dataset: CIFAR100
  transfer_path_train: cifar100/cifar100_train.beton
  transfer_path_val: cifar100/cifar100_test.beton
transfer_training:
  transfer_ffcv: True
  upsample: True
  decoder_train: simple
  decoder_val: simple
  transfer_epochs: 15
  transfer_lr: 0.1
  transfer_weight_decay: 0.0005
  transfer_momentum: 0.9
  transfer_lr_scheduler: cyclic
  transfer_step_size: 10
  transfer_gamma: 0.1
  transfer_label_smoothing: 0.0
  transfer_lr_milestones: ""
  transfer_lr_peak_epoch: 5
  transfer_granularity: global
  transfer_eval_epochs: 100
